version: '2.1'
services:
    postgres:
        image: postgres:9.6
        volumes:
            - ${POSTGRES_DATA_MOUNT}:/var/lib/postgresql/data
        env_file:
            - ./postgres/postgres.env

    webserver:
        image: ccastleberry/airflow:${TAG}
        restart: always
        depends_on:
            - postgres
        env_file:
            - ./airflow-webserver/.airflow.env
        volumes:
            - ${AIRFLOW_DAG_MOUNT}:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        privileged: true
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3